# Generated by Django 3.2.7 on 2021-09-29 21:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('main_url', models.CharField(max_length=200)),
                ('rss_url', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('aggregated', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('website', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aggregator.website')),
            ],
        ),
    ]
