# Generated by Django 3.2.7 on 2021-09-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_auto_20210929_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='rss_parent_node',
            new_name='new_author_field',
        ),
        migrations.AddField(
            model_name='website',
            name='new_content_field',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='new_link_field',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='new_published_field',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='new_title_field',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
