# Generated by Django 3.2.7 on 2021-09-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_auto_20210929_1728'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='News',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='new_author_field',
            new_name='news_author_field',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='new_content_field',
            new_name='news_content_field',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='new_link_field',
            new_name='news_link_field',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='new_published_field',
            new_name='news_published_field',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='new_title_field',
            new_name='news_title_field',
        ),
    ]
