# Generated by Django 3.2.7 on 2021-09-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_auto_20210929_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='guid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='news_guid_field',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
