# Generated by Django 3.2.7 on 2021-09-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0006_alter_news_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
    ]
