# Generated by Django 3.2.7 on 2021-09-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0010_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='clicks_on_source',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
