# Generated by Django 3.2.7 on 2021-09-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0011_news_clicks_on_source'),
    ]

    operations = [
    ]
